site_name: Notes
site_url: "https://rishikeshvadodaria.github.io/mkdocs/"

nav:
  - Home: index.md
  - RL Unit 1: RL-Unit-1.md

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - content.code.annotate

extra:
  generator: false  # Removes "Powered by MkDocs Material" footer

markdown_extensions:
  - toc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.betterem
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.escapeall
  - pymdownx.progressbar
  - attr_list
  - md_in_html

extra_javascript:
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js

plugins:
  - search
  - mermaid
