site_name: Notes
site_url: "https://rishikeshvadodaria.github.io/mkdocs/"

nav:
  - Home: index.md
  - RL Unit 1: RL-Unit-1.md

theme:
  name: material
  palette:
    - scheme: slate  # Enables dark mode
      primary: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default  # Light mode
      primary: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mermaid/10.4.0/mermaid.min.js

markdown_extensions:
  - toc
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details

extra:
  generator: false
